### ISSUE TITLE
Please fix code repo link

### ISSUE THREAD

**Issue by pcav** [mkondratyev85/raster_tracer#1]
https is repeated twice

**Comment by mkondratyev85** [comment]
Fixed. Thanks.

**Comment by pcav** [comment]
Still wrong in https://plugins.qgis.org/plugins/raster_tracer/

**Comment by pcav** [comment]
I fixed it by hand in the web app interface.
